export const STUDIO_PREVIEW_CHANNEL = 'neosmartui-studio-preview';
const forbiddenTags = 'script,style,link,iframe,object,embed,base,meta';
const unsafeAttributes = new Set(['style','srcdoc','srcset','action','formaction']);
const fail = (message) => { throw new TypeError('[studio-preview-kernel] ' + message); };
export function assertSafeCss(css,label='preview CSS'){if(typeof css!=='string')fail(label+' must be text');if(/<\/style/i.test(css))fail(label+' must not close its style element');if(/@import\b/i.test(css))fail(label+' must not import external CSS');if(/url\(\s*['"]?\s*(?:https?:|\/\/)/i.test(css))fail(label+' must not reference network URLs');return css}
export function assertSafeFixture(fixture){if(typeof fixture!=='string')fail('fixture must be text');const template=document.createElement('template');template.innerHTML=fixture;if(template.content.querySelector(forbiddenTags))fail('fixture contains forbidden executable or embedding markup');for(const element of template.content.querySelectorAll('*')){for(const attribute of [...element.attributes]){const name=attribute.name.toLowerCase();const value=attribute.value.trim();if(name.startsWith('on'))fail('fixture inline event handlers are forbidden');if(unsafeAttributes.has(name))fail('fixture attribute '+name+' is forbidden');if(name==='href'&&value&&!value.startsWith('#'))fail('fixture links must remain fragment-local');if((name==='src'||name==='poster')&&value&&!/^data:image\/(?:png|jpeg|gif|webp);base64,/i.test(value))fail('fixture media must use inline raster data images')}}return fixture}
export function assertStandaloneModuleSource(source,label='preview module'){if(typeof source!=='string')fail(label+' source must be text');if(/^\s*import\s+(?!\()/m.test(source)||/^\s*export\s+[^;]+\s+from\s+['"]/m.test(source))fail(label+' must be a self-contained repository module');return source}
const safeJson=(value)=>JSON.stringify(value).replaceAll('<','\\u003c').replaceAll('>','\\u003e').replaceAll('&','\\u0026');
const makeNonce=()=>{const bytes=new Uint8Array(18);crypto.getRandomValues(bytes);let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')};
export function createIsolatedPreview({container,renderId,title,themeCss,harnessCss,componentCss,fixture,manifest,state,runtimeSource,adapterSources,controllerSource}){
 if(!(container instanceof Element))fail('preview container must be an Element');if(typeof renderId!=='string'||!renderId)fail('renderId is required');assertSafeCss(themeCss,'Theme CSS');assertSafeCss(harnessCss,'preview harness CSS');assertSafeCss(componentCss,'component CSS');assertSafeFixture(fixture);if(!manifest||manifest.schema!=='neosmartui/component-preview@1')fail('preview manifest identity is invalid');const realization=manifest.stateRealization?.[state];if(!realization)fail('state is not declared by the preview manifest');
 assertStandaloneModuleSource(runtimeSource,'preview runtime');const checkedAdapterSources={};for(const [path,source] of Object.entries(adapterSources||{}))checkedAdapterSources[path]=assertStandaloneModuleSource(source,'shipping adapter '+path);const checkedControllerSource=controllerSource?assertStandaloneModuleSource(controllerSource,'preview controller'):null;const token=makeNonce();
 const csp=["default-src 'none'","style-src 'nonce-"+token+"'","script-src 'nonce-"+token+"' blob:","img-src data:","connect-src 'none'","font-src 'none'","media-src 'none'","worker-src 'none'","child-src 'none'","frame-src 'none'","object-src 'none'","manifest-src 'none'","base-uri 'none'","form-action 'none'"].join('; ');
 const bootstrap=["const manifest = "+safeJson(manifest)+";","const state = "+safeJson(state)+";","const runtimeSource = "+safeJson(runtimeSource)+";","const adapterSources = "+safeJson(checkedAdapterSources)+";","const controllerSource = "+safeJson(checkedControllerSource)+";","const channel = "+safeJson(STUDIO_PREVIEW_CHANNEL)+";","const renderId = "+safeJson(renderId)+";","const root = document.getElementById('preview-root');","const moduleUrls = [];","const moduleUrl = (source) => { const url = URL.createObjectURL(new Blob([source], { type: 'text/javascript' })); moduleUrls.push(url); return url; };","try {"," const runtimeUrl = moduleUrl(runtimeSource);"," const adapterUrls = Object.fromEntries(Object.entries(adapterSources).map(([path, source]) => [path, moduleUrl(source)]));"," const controllerUrl = controllerSource ? moduleUrl(controllerSource) : null;"," const runtime = await import(runtimeUrl);"," const mounted = await runtime.mountPreviewBindings({root,manifest,moduleResolver:(path)=>{const url=adapterUrls[path];if(!url)throw new Error('Missing shipping adapter module '+path);return import(url)}});"," const current = manifest.stateRealization[state];"," if(current.mode==='controller'){if(!controllerUrl)throw new Error('Controller source is required for state '+state);const controller=await import(controllerUrl);runtime.applyPreviewController({root,manifest,state,controller,helpers:mounted.helpers})}"," window.parent.postMessage({channel,type:'ready',renderId,component:manifest.component,state,mode:current.mode},'*');","} catch(error) {"," window.parent.postMessage({channel,type:'error',renderId,message:String(error&&error.message?error.message:error)},'*');","}","window.addEventListener('pagehide',()=>{for(const url of moduleUrls)URL.revokeObjectURL(url)},{once:true});"].join('\n');
 const html=['<!doctype html><html lang="en"><head><meta charset="utf-8" />','<meta name="viewport" content="width=device-width, initial-scale=1" />','<meta http-equiv="Content-Security-Policy" content="'+csp.replaceAll('"','&quot;')+'" />','<style nonce="'+token+'">'+themeCss+'\n'+harnessCss+'\n'+componentCss+'</style>','</head><body>','<main id="preview-root" class="ns-studio-theme">'+fixture+'</main>','<script type="module" nonce="'+token+'">'+bootstrap.replaceAll('</script','<\\/script')+'</script>','</body></html>'].join('');
 container.replaceChildren();const iframe=document.createElement('iframe');iframe.id='preview-frame';iframe.title=title||'NeoSmartUI component preview';iframe.setAttribute('sandbox','allow-scripts');iframe.dataset.renderId=renderId;iframe.srcdoc=html;container.append(iframe);
 let destroyed=false;return{iframe,renderId,destroy(){if(destroyed)return;destroyed=true;iframe.remove()}};
}
